export const FETCHING_TIME = 'FETCHING_TIME';
export const FETCHING_FAILED = 'FETCHING_FAILED';

export const ERROR_STATUS_ADDED = 'ERROR_STATUS_ADDED';
export const SUCCESS_STATUS_ADDED = 'SUCCESS_STATUS_ADDED';
export const STATUS_CLEARED = 'STATUS_CLEARED';

export const LISTING_DATA_FETCHING = 'LISTING_DATA_FETCHING';
export const DATA_GATHERING = 'DATA_GATHERING';

export const REPORT_CREATED = 'REPORT_CREATED';
export const REPORT_FETCHED = 'REPORT_FETCHED';
